261 feature/ticket subscription mobile + new mobile app style
WildCodeSchool/2209-wns-adleman-bordolamif pull request #286
Opened 2023-05-26 12:53 UTC by JoffreyChevalier

2023-05-26 13:26 UTC, AxelCabanat requested changes

2023-05-26 13:26 UTC, AxelCabanat commented on client_mobile/src/screen/TicketScreen.tsx
> +    };
Peut-être définir la fonction hors du useEffect pour améliorer la compréhension de ce hook.

2023-05-26 13:26 UTC, AxelCabanat commented on client_mobile/graphQL/query/ticketQuery.ts
> +export const GET_ALL_TICKETS_OF_THE_DAY = gql`
Attention au nommage, avec le bon filter tu peux choper tous les tickets de l'année avec GET_ALL_TICKETS_OF_THE_DAY

2023-05-26 13:35 UTC, SandraVsn submitted a review, later dismissed

2023-06-21 07:31 UTC, AxelCabanat submitted a review, later dismissed

2023-06-21 07:42 UTC, AxelCabanat commented on client_mobile/%ProgramData%/Microsoft/Windows/UUS/State/_active.uusver
> +923.330.111.0
Ton fichier est toujours là ^^'

2023-06-21 08:10 UTC, closed without merging